@PG-28
Feature: A print from step definition feature

	@TEST_PG-27
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition	
			@b
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition			
			@c
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition			
			@d
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
			Given I print from step definition
		    And I print from step definition
			@e
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition			
			@f
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition			
			@g
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition						
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition			
			@i
	Scenario: A print from step definition feature
		Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition
		    Given I print from step definition
		    And I print from step definition	
			
